### ISSUE TITLE
Question: How to register Scoped Repository/Service?

### ISSUE THREAD

**Issue by acambule** [danpdc/cwk.MinimalApis.SmartModules#8]
Hi there,

not using SmartModules with minimal API i would do something like this:

```c#
program.cs:
builder.Services.AddScoped<IMyRepository, MyRepository>();
builder.Services.AddScoped<IMyService, MyService>();
...

var scope = app.Services.CreateScope();
var myService = scope.ServiceProvider.GetRequiredService<IMyService>();
  
app.MapPost("/api/my", (MyDto myDto) => mySerice.WriteMyToDb(myDto));

```

With SmartModules im trying like this:

```c#
myModule.cs:

...

public override IEndpointRouteBuilder MapEndpointDefinitions(IEndpointRouteBuilder app)
{
    using var scope = _serviceProvider.CreateScope(); 
    var myService = scope.ServiceProvider.GetRequiredService<IMyService>();
    
    app.MapPost(apiRoute, (MyDto myDto => myService.WriteMyToDb(myDto));
        
    return app;
}

```

So now it stops on `GetRequiredService`, with Error:

`No service for type '...IMyService' has been registered."`

Looking at both code snippets it looks like missing whats behind these two lines:
```c#
builder.Services.AddScoped<IMyRepository, MyRepository>();
builder.Services.AddScoped<IMyService, MyService>();
```
that does the registering.

But how would i do that using SmartModules?

Thanks and regards
Antonio

**Comment by danpdc** [comment]
Hello. Thank you very much for your question. 
I have right now looked into it and unfortunately I was not able to reproduce it. 

```csharp
builder.Services.AddScoped<MyService>();
```
And in my module:
```csharp
using var scope = _serviceFactory.CreateScope();
            var ctx = scope.ServiceProvider.GetRequiredService<ThoughtfulDbContext>();
            var myService = scope.ServiceProvider.GetRequiredService<MyService>();

            endpoints.MapSmartGet("/api/authors",  (IMediator mediator) 
                => myService.SomeGuid)
                .WithName("GetAllAuthors")
                .WithDisplayName("Authors")
                .WithTags("Authors")
                .Produces<List<AuthorGetDto>>()
                .Produces(500);
```

Just note that I have switch to use MyService to return a GUID. I have tried it out both with injecting the IServiceProvider and IServiceScopeFactory in my module's constructor.and it worked with both. 

However, no matter if you are using SmartModules or not, this approach is surely not optimal at al. Even if you resolve the scope there, the service instance that gets created there will remain and be reused through the entire lifetime of the app. So even if you add MyService as scoped, the way you use it, the created instance will de facto behave as singleton. 

With or without smartModules, you should inject the needed service in the delegate you provide in your Map method. In that case it will behave like singleton.

**Comment by danpdc** [comment]
Do you maybe have the entire solution on GitHub so that I can take a look?

**Comment by acambule** [comment]
Hi Dan,

thanks for looking over it. I've created a prototype of what i'm working on, that shows my problem. I let out the database stuff and made an ICollection to add something, retrieve the list and retrieve by Id. It's been a quick and dirty work, but the api works when i do not use Smartmodules. 

As I'm quite new to .NET API development probably i misunderstand something very basic on it. 
If you were so kind to take a look at it.

Thank you and regards
Antonio

Projectlink: https://github.com/acambule/prototype

**Comment by danpdc** [comment]
The problem is here:
```csharp
var prototypeService = scope.ServiceProvider.GetRequiredService<PrototypeService>();
```
When resolving services, you should resolve them using the interface that you have provided, not the implementation:
```csharp
var prototypeService = scope.ServiceProvider.GetRequiredService<IPrototypeService>();
```

In Program.cs you did it correctly:
```csharp
var prototypeService = scope.ServiceProvider.GetRequiredService<IPrototypeService>();
```

I have tested it and it works. 
However, this is IMPORTANT. You should not use scoped services like this. The way you use them, you create a scope when the application starts and that scope remains active until the application shuts down. You end up having object instances that will behave like singletons. 

You should inject your services directly in the delegate:
```csharp
public override IEndpointRouteBuilder MapEndpointDefinitions(IEndpointRouteBuilder app)
        {
            //using var scope = _serviceProvider.CreateScope();
            //var prototypeService = scope.ServiceProvider.GetRequiredService<PrototypeService>();

            app.MapGet(apiRoute, (IPrototypeService prototypeService) 
                    => prototypeService.ReadPrototypes())
                .WithName("GetPrototypes")
                .WithDisplayName("Get Prototypes");


            app.MapGet(apiRoute+ "/{Id}", (Guid Id, IPrototypeService prototypeService) 
                    => prototypeService.ReadPrototype(Id))
                .WithName("GetPrototype")
                .WithDisplayName("Get Prototype");

            app.MapPost(apiRoute, (PrototypeDto prototypeDto, IPrototypeService prototypeService) 
                    => prototypeService.WritePrototype(prototypeDto))
                .WithName("PostPrototype")
                .WithDisplayName("Post Prototype");


            return app;
        }
```
Notice here I have commented out your service scope creation.
The same goes if you want to do this in your Program.cs file. 

Hope I was able to clarify this issue. Let me know if there is anything else.

**Comment by acambule** [comment]
Hi Dan,

I see it has been less an Smartmodules problem than an general understanding. 
Now it works like it should. Thank you also for the tip, how to implement it the better way.
I've updated the prototype project, in case someone like me needs an other example.

regards 
Antonio
